### ISSUE TITLE
loading multiple files can overwrite the same word

### ISSUE THREAD

**Issue by holdfenytolvaj** [rubenv/angular-gettext-tools#128]
For us some of the language files are separated (at least in the dev environment), but can contain the same word in different context.
Currently the last loaded file overwrites the rest for the same word.
Since it's rather a small change I just copy it here, rather then creating a pull request. Thanks!

The catalog->setStrings function 

``` javascript
                // Expand single strings for each context.
                for (var context in val) {
                    var str = val[context];
                    val[context] = angular.isArray(str) ? str : [str];
                }
                this.strings[language][key] = val;
```

probably would be better like this:

``` javascript
                if (!this.strings[language][key]) {
                    this.strings[language][key] = {};
                }
                // Expand single strings for each context.
                for (var context in val) {
                    var str = val[context];
                    this.strings[language][key][context] = angular.isArray(str) ? str : [str];
                }
```

**Comment by mattbrunetti** [comment]
@holdfenytolvaj Are you using this fix?

We don't have a need for the "context" feature *yet* but we likely will! 

I'm a bit worried that this repo isn't actively maintained. 

A community maintained fork might be a good idea...

**Comment by holdfenytolvaj** [comment]
Hmm it seems I've made a mistake .. and this fix is for angular-gettext not for the tools. I will made a pull request there then. Yes we do use context, although we don't have real clients yet that use translation.
