### ISSUE TITLE
The use of the $ (dollar) symbol throws an error

### ISSUE THREAD

**Issue by aissaghouti** [rubenv/angular-gettext-tools#168]
Hi there,

I have the following error "Error parsing app/controllers/somefile.js at line 3179 column 123".

Here is the accused line: `$gt: new Date(new Date(from).setHours(00, 00, 00, 999))` extracted from this code: 
```
var options = {
    query: {
        personID: myPersonID,
        productID: myProductID,
        orderDate: {
            $gt: new Date(new Date(from).setHours(00, 00, 00, 999)),
            $lt: new Date(new Date(to).setHours(23, 59, 59, 999))
        }
    },
    limit: 1000
};
```
I think it's related to the using of `$` (symbol used for MongoDB queries). Because when I remove the `$gt` and `$lt` lines, no error is logged.

Do you have any idea on what's going on here?
Thanks.

**Comment by rubenv** [comment]
That sounds like an error in the HTML parser. We're using `babylon`, it might be better to file an issue there: https://github.com/babel/babel

**Comment by aissaghouti** [comment]
Thanks @rubenv, here is the issue: https://github.com/babel/babylon/issues/511
