### ISSUE TITLE
.pot overriding controller text

### ISSUE THREAD

**Issue by arisah-ijeoma** [rubenv/angular-gettext-tools#172]
Say I have login.html and login_controller.js
When I annotate these, I get the right texts in .pot

However when I translate a different file like food.html and food_controller.js, text for login_controller and food_controller are not found

All I have are the .html texts

**Comment by ngehlert** [comment]
is this still relevant? can you try to reproduce a basic example of your project e.g. in stackblitz?

**Comment by arisah-ijeoma** [comment]
no it's not

thanks
