### ISSUE TITLE
Cannot extract "constructor"

### ISSUE THREAD

**Issue by AlexSchuetz** [rubenv/angular-gettext-tools#188]
The text "constructor" doesn't get extracted.

Here is an example. The following HTML will have no extracted text:
`
<translate>constructor</translate>
`

This is case sensitive, because this works as expected:
`
<translate>Constructor</translate>
`

Other possible keywords don't seem to produce this issue. I tested "if" and "function".

**Comment by rubenv** [comment]
There's nothing in the code that handles `constructor` specifically, so that's very strange.

Could you make a pull request with a failing unit test?

**Comment by AlexSchuetz** [comment]
#189

**Comment by rubenv** [comment]
Whew, that was interesting!

`constructor` was clashing with a JS built-in, thus getting ommitted.
Anyway, fixed pushed and released to NPM as `v2.3.13`.

Thanks a lot!

**Comment by AlexSchuetz** [comment]
Wow. That was fast. Thank you.
