### ISSUE TITLE
Do not introduce breaking changes in minor versions

### ISSUE THREAD

**Issue by djungowski** [rubenv/angular-gettext-tools#194]
So I just updated from 2.3.14 to 2.3.16 and had major issues. Looking at the code, I saw that in this commit/merge https://github.com/rubenv/angular-gettext-tools/commit/b3607fccd59c4349cc3ee29f6378eafc7658c930 you bumped from Typescript 2 to Typescript 3.

At least this should have resulted in a version 2.4.0, also see https://docs.npmjs.com/about-semantic-versioning about this. 

I know this sounds nitpicky, but people do define their versioning for upgrades in the package.json for good reasons to sometimes only include minor or patch releases.

**Comment by rubenv** [comment]
Apologies for that, am well aware of semver. I'm just used to Go, which always guarantees backwards compatibility on a language level.

Just push `v2.4.1` and `v2.3.18` to solve your problems.
