### ISSUE TITLE
Please support *.ejs

### ISSUE THREAD

**Issue by Fonger** [rubenv/angular-gettext-tools#69]
I'm using grunt-angular-gettext and I find ejs files are ignored even though I specify *.ejs

ejs shoud be treated as 'html'

I find it very inconvenient because I have to manually modify this file in node_modules.

I hope you can add .ejs support or as many types as possible.

It's just updated to 2.0.0 but I don't see any changes but "Copyright 2015"

**Comment by rubenv** [comment]
There have been a lot of changes: https://github.com/rubenv/angular-gettext-tools/compare/v1.0.6...v2.0.0

I assume EJS is like ERB, but for JS?

Just mark the `ejs` extension as `html` in your grunt options:
```js
nggettext_extract: {
  "all": {
    "files": {
      "po/template.pot": [
        "src/**/*.html",
      ]
    },
    "options": {
      "extensions": {
        "html": "html",
        "ejs": "html",
        "js": "js"
      }
    }
  }
}
```

If you want support out of the box, please submit a pull request with a sample file and a test case: that way we're sure that things keep working.

**Comment by Fonger** [comment]
Just submit a pull request and test for ejs. Thank you :)
https://github.com/rubenv/angular-gettext-tools/pull/70

**Comment by rubenv** [comment]
`angular-gettext-tools@2.0.1` and `grunt-angular-gettext@2.0.1` released to NPM. Thanks again!
