### ISSUE TITLE
Extraction support for HAML

### ISSUE THREAD

**Issue by jaybloke** [rubenv/angular-gettext-tools#71]
Hi Ruben,

Does your extraction tool support HAML. I'm using Rails + HAML for my templates and would of course like to take advantage of your excellent angular-gettext module. If not, I guess one possibility would be to build a task that pre-processes the haml by converting it to plain html. Could you recommend any library that might be up to the task of converting HAML to HTML?

Cheers
J

**Comment by rubenv** [comment]
Can't recommend anything there. Doesn't haml have this built-in?

But anyway, compiling to HTML first is what I recommend and do with Jade.

**Comment by jaybloke** [comment]
Thanks Ruben... i'll give Jade a try.
