### ISSUE TITLE
config location of destination folder in nggettext_compile command

### ISSUE THREAD

**Issue by NVK15** [rubenv/angular-gettext-tools#74]
Hi,

I am trying to generate JSON output file using PO files. Below is the configuration i have used:

 nggettext_compile: {
            all: {
                options: {
                    format: "json"
                },
                files: [
                    {
                        expand: true,
                        cwd:"../",
                        src: ["po/*.po"],
                        dest: 'lang/',
                        ext: ".json"
                    }
                ]
            },
        },

The PO files are present in folder named: "PO" as mentioned in 'src'. And i want to output the JSON files in "lang" folder which is at the same level as "PO" folder. I somehow cant get this command working. Neither the folder nor JSON files are generated. Can anyone help me with correct configuration?

Thanks.

**Comment by gabegorelick** [comment]
FYI, issues like this should be filed against [grunt-angular-gettext](https://github.com/rubenv/grunt-angular-gettext).

**Comment by NVK15** [comment]
thanks for directing!
