### ISSUE TITLE
angular-gettext fails to replace text with special characters

### ISSUE THREAD

**Issue by NVK15** [rubenv/angular-gettext-tools#76]
Hi,

I have the following in my HTML page:
&lt;span translate&gt;Total duration [min]&lt;/span&gt;

I could extract this string into POT, and have the translated string compiled into JS file. The translations get replaced for all strings, except for strings which have special character like one mentioned above.

i get:  [MISSING]: Total duration [min] . Where ever special characters are present, it is failing to replace.
Is there anything i am missing to add?

Thanks in advance.

**Comment by gabegorelick** [comment]
This is a known issue, although I can't find the bug #.
