### ISSUE TITLE
Obsolete PO entries should be handled

### ISSUE THREAD

**Issue by pakal** [rubenv/angular-gettext-tools#77]
For now, compile() discards fuzzy entries, but keeps obsolete enties ; this should be the contrary imho, or at least configurable by options (skipFuzzy, skipObsolete...).

Please tell me what the way to go is, I may prepare a PR for it.

**Comment by rubenv** [comment]
This is how all gettext tools work. The opposite is not what you want: it
totally breaks the concept of fuzzy strings.

Keeping obsoletes for a while isn't much of an issue: the .po file is only
used during development. We frequently see strings disappearing and
reappearing during design iterations, so it's always nice to be able to
recuperate them.

I highly recommend you stick with the default behaviour: there's thinking
behind it and it makes sense.

**Comment by pakal** [comment]
I might have not been clear here : it's totally OK that obsolete strings are kept (commented with #~) in the PO file at each gettext extraction, because indeed they might serve later. 

The problem is that these obsolete strings are exported to json by the **compile** task, i.e even when that json is intended for prod. But from what I understand of gettext concepts, obsolete strings should never leave the PO file, neither when compiling to MO binary, nor to JSON for use with angularjs apps.

**Comment by rubenv** [comment]
Ah yes, that's a bug then. We shouldn't output them.

**Comment by rubenv** [comment]
Published `angular-gettext-tools@2.0.3` to NPM.

Simply `rm -rf node_modules; npm install` and you should have the fix.

**Comment by pakal** [comment]
thanks a lot  :)
