### ISSUE TITLE
Esprima is out of date - esprima 2 is released, and it supports ES6. 

### ISSUE THREAD

**Issue by huston007** [rubenv/angular-gettext-tools#84]
Now I can't directly extract text from es6 scripts

**Comment by rubenv** [comment]
Care to submit a test file we can use?

**Comment by huston007** [comment]
Just es6 imports brokes esprima
```
import 'hello.js';

i18n('Translate me!');
```

**Comment by huston007** [comment]
Bad news is that esprima 2.1 still throwing that error, so I don't actually know how to use angular-gettext-tools with ES6.

**Comment by huston007** [comment]
Looks like we should use esprima fork - `espree` https://github.com/eslint/espree, which fully supports ES6

**Comment by princed** [comment]
Allowing custom parsers like `esprima-fb`, `espree` etc. (like it [done in ESLint](http://eslint.org/docs/configuring/#specifying-parser)) and custom `espirima.parse` params would work as well.

**Comment by gabegorelick** [comment]
Transpiling first and then using angular-gettext will also work.

**Comment by smehrbrodt** [comment]
Created a pull request for this: https://github.com/rubenv/angular-gettext-tools/pull/87
