### ISSUE TITLE
JavaScript - extraction from filters in strings

### ISSUE THREAD

**Issue by Akarienta** [rubenv/angular-gettext-tools#88]
Is it possible to have also extraction from filters which are in strings in JavaScript files? Angular-gettext supports it.

e.g.
```javascript
app.config(function($stateProvider) {
  $stateProvider.state('welcome', {
     url : '/',
     templateUrl: 'index.html',
     ncyBreadcrumb : {
        label: '{{"Home"|translate}}'
     }
  });
});
```

**Comment by gabegorelick** [comment]
Why would you need this versus just calling
gettextCatalog.getString('Home')?

**Comment by Akarienta** [comment]
It is not possible in a config phase: https://github.com/rubenv/angular-gettext/issues/168

**Comment by gabegorelick** [comment]
I'd rather support using `gettext` as a provider than implement this. There's a PR for that out there already. I'll see if we can get it merged in.
