### ISSUE TITLE
Misleading error when building po files with blank lines before headers

### ISSUE THREAD

**Issue by aaronbloom** [rubenv/angular-gettext-tools#89]
Currently compiling po files that have blank lines before the headers (e.g. language header) gives the following error.

    > grunt nggettext_compile:all
    Running "nggettext_compile:all" (nggettext_compile) task
    Warning: No Language header found! Use --force to continue.
    
    Aborted due to warnings.

As an error it feels fairly misleading.

Example file that does not build:

    msgid ""
    msgstr ""
    
    "Language: es-es\n"
    

Example file that does build:

    msgid ""
    msgstr ""
    # <- note the comment line
    "Language: es-es\n"

**Comment by rubenv** [comment]
> Currently compiling po files that have blank lines before the headers (e.g. language header)

Are those even valid .po files?

**Comment by aaronbloom** [comment]
They might well not be - I could not find any particular rule against it. If anything I thought it would be productive to document the error for this particular case.

**Comment by rubenv** [comment]
I'll happily accept a pull request for that one. Will need to go into pofile: https://github.com/rubenv/pofile

Closing this issue since it's not related to angular-gettext-tools.
