### ISSUE TITLE
Loading "compile.js" tasks...ERROR

### ISSUE THREAD

**Issue by NVK15** [rubenv/angular-gettext-tools#93]
Hi,

I have 'nggettext_extract' task defined in my grunt file and when i try to execute i get the following error:

Loading "compile.js" tasks...ERROR>> Error: Cannot find module 'lodash.isarray'
Loading "extract.js" tasks...ERROR
>> Error: Cannot find module 'lodash.isarray'

This was working fine before, i have version 2.1.0 of grunt-angular-gettext.

Can anyone point me how to solve this?

Thanks in advance.

**Comment by rubenv** [comment]
Have you tried running `npm install`?

**Comment by NVK15** [comment]
yes, 'angular-gettext' and 'grunt-angular-gettext' are installed globally. should i have do anything more?

**Comment by rubenv** [comment]
I'm not sure if a global install works for grunt tasks. I highly recommend installing them in the project.

**Comment by NVK15** [comment]
i tried installing in project as well, doesn't help, i get the same error.

**Comment by rubenv** [comment]
I have no idea what this might cause.

Could you try getting https://github.com/rubenv/angular-gettext-example, doing an `npm install` and a `grunt` run?

That should work. If so, you have an example of how things should work. If not, there will probably something wrong with your Node.JS install.

**Comment by gabegorelick** [comment]
Closing this while we wait for more info. If this is an issue, it probably belongs in grunt-angular-gettext anyway.
